packageManagers:
  chocolatey:
    enabled: true
    safeMode: true
    dryRun: false
    rootCommand: choco

    globalSwitches: '--no-progress --nocolor'
    safeModeSearchSwitch: '{{#if safeMode}}--approved-only --not-broken{{/if}}'

    filterInstalledCommand: '{{rootCommand}} list {{globalSwitches}} -l "{{package.Name}}" {{#if package.Version}}-ea --version {{package.Version}}{{/if}}'
    getInstalledPackageCommand: '{{rootCommand}} list {{globalSwitches}} -l -e "{{package.Name}}" {{#if package.Version}}-a --version {{package.Version}}{{/if}}'
    searchCommand: '{{rootCommand}} search {{globalSwitches}} "{{package.Name}}" {{#if package.Version}}-ea --version {{package.Version}}{{/if}} {{> safeModeSearchSwitch}}'
    installCommand: '{{rootCommand}} install {{globalSwitches}} -y {{#if dryRun}}--noop{{/if}} {{#if safeMode}}--exit-when-reboot-detected{{/if}} "{{package.Name}}" --version {{package.Version}}'
    uninstallCommand: '{{rootCommand}} uninstall {{globalSwitches}} -y {{#if dryRun}}--noop{{/if}} {{#if safeMode}}--exit-when-reboot-detected{{/if}} "{{package.Name}}" --version {{package.Version}}'
    upgradeCommand: '{{rootCommand}} install {{globalSwitches}} -y {{#if dryRun}}--noop{{/if}} {{#if safeMode}}--exit-when-reboot-detected{{/if}} "{{package.Name}}" --version {{package.Version}}'
    isInstalledCommand: '{{rootCommand}} search {{globalSwitches}} -l -e "{{package.Name}}" {{#if package.Version}}--version {{package.Version}}{{/if}}'
    getExistingInstalledVersionCommand: '{{rootCommand}} search {{globalSwitches}} -l -e "{{package.Name}}"'
    isPackageAvaiableForInstallCommand: '{{rootCommand}} search {{globalSwitches}} -e "{{package.Name}}" {{#if package.Version}}-a --version {{package.Version}}{{/if}} {{> safeModeSearchSwitch}}'