packageManagers:
  chocolatey:
    enabled: true
    safeMode: true
    dryRun: true
    rootCommand: choco

    globalSwitches: '--no-progress --nocolor'
    safeModeSearchSwitch: '{{#if safeMode}}--approved-only --not-broken{{/if}}'

    getInstalledCommand: '{{rootCommand}} list {{globalSwitches}} -l "{{package.Name}}" {{#if package.Version}}-ea --version {{package.Version}}{{/if}}'
    searchCommand: '{{rootCommand}} search {{globalSwitches}} "{{package.Name}}" {{#if package.Version}}-ea --version {{package.Version}}{{/if}} {{> safeModeSearchSwitch}}'
    installCommand: '{{rootCommand}} install {{globalSwitches}} -y {{#if dryRun}}--noop{{/if}} {{#if safeMode}}--exit-when-reboot-detected{{/if}} {{package.Name}} --version {{package.Version}}'
    isInstalledCommand: '{{rootCommand}} search {{globalSwitches}} -l {{package.Name}} {{#if package.Version}}--version {{package.Version}}{{/if}}'
    getExistingInstalledVersionCommand: '{{rootCommand}} search {{globalSwitches}} -l -e {{package.Name}}'
    isPackageAvaiableForInstallCommand: '{{rootCommand}} search {{globalSwitches}} -e {{package.Name}} {{#if package.Version}}-a --version {{package.Version}}{{/if}} {{> safeModeSearchSwitch}}'