packageManagers:
  chocolatey:
    enabled: true
    rootCommand: choco
    getInstalledCommand: '${rootCommand} list -l --no-progress --nocolor'
    searchCommand: '${rootCommand} search --no-progress --nocolor ${query}'
    installCommand: '${rootCommand} install -y --no-progress --nocolor --noop'